High Misty Seahorse

high

# Initiating a crosschain claim may result in funds stuck in the receiver chain when call fails.

## Summary

Initiating a crosschain claim may result in funds stuck in the receiver chain when call fails.

## Vulnerability Detail

When a user calls `Satellite.initiateClaim()` a claim is sent to the distributor via a crosschain [call](https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/Satellite.sol#L79-L100).
The `delegate` address is set to the `address(0)` and thus the user will not be able to re-initiate the claim.

Also the `connext.xcall()` is not handled properly according to the [connext documentation](https://docs.connext.network/integrations/guides/handling-failed-xcalls). The `msg.value` sent will get stuck in the receiver chain and there will be no `delegate` that can re-try the claim and no correct handling in case this call fails.

Handling of failed calls is done in `CrosschainMerkleDistributor.xReceive()` where  `_settleClaim()` and `_executeClaim()` are called. A try-catch block is not implemented and this may lead to funds getting stuck on the receiver contract.

These could very well be two separate issues.

## Impact

This is a high severity issue as user funds may get stuck in the receiver chain and there is no way of accessing them.

## Code Snippet

```solidity
function initiateClaim(uint256 total, bytes32[] calldata proof) public payable {
    ....
    // Send claim to distributor via crosschain call
    bytes32 transferId = connext.xcall{ value: msg.value }(
      _distributorDomain, // destination domain
      address(distributor), // to
      address(0), // asset
      address(0), // delegate, only required for self-execution + slippage
      0, // total
      0, // slippage
      abi.encodePacked(msg.sender, _domain, total, proof) // data
    );
    ....
  }
```

## Tool used

Manual Review

## Recommendation

Consider setting  `delegate` address to `msg.sender` so that the user can re-initiate a claim and handle failed calls properly on the receiver chain per [connext docs](https://docs.connext.network/integrations/guides/handling-failed-xcalls).

